name: pusa_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  #FIREBASE
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  #BLOC
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  #Shared Preferences
  shared_preferences: ^2.5.3

  #Image Picker
  image_picker: ^1.2.0

  #Modal Sheet
  modal_bottom_sheet: ^3.0.0

  #MQTT broker
  mqtt_client: ^10.11.1

  #Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/cat_login1.png
